version: "3"
services:

  back:
    build: ./api
    image: back
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    ports:
      - "5000:5000"

  front:
    build: ./client
    image: front
    ports:
      - "5173:5173"
    depends_on:
      - back
